apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-
spec:
  params:
  - name: source-repo
    value: https://github.com/OpheliaHuang/express-sample-app
  - name: image-repo
    value: quay.io/ophelia_huang/my-express
  pipelineRef:
    name: nodejs
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce